acronyms_dict ={
"3PL":"3rd Party Logistics", 
"5S":"Sort, Straighten, Shine, Standardize and Sustain ", 
"A2LA":"American Association for Laboratory Accreditation", 
"AA ":"Arithmetical Average", 
"AACE":"American Association of Cost Engineers", 
"AAMA":"American Architectural Manufacturers Association", 
"AAP":"Automated Accounts Payable", 
"AAP ":"Automated Accounts Payable", 
"AB":"Accreditation Body", 
"ACA":"American Coatings Association", 
"Accounting String":"Accounting String", 
"ACGIH":"American Conference of Governmental Industrial Hygienists", 
"ACH":"Automated Clearing House", 
"ACH; ACH Payment":"Automated Clearing House", 
"ACL":"Access Control Layer ", 
"ACLASS":"ACLASS Accreditation Services", 
"ACM":"Asbestos Containing Material", 
"ACSI":"American Customer Satisfaction Index", 
"ACT":"Application Compatibility Toolkit", 
"Action":"Action", 
"ACW":"After Call Work", 
"AD":"Active Directory", 
"ADAMS":"Agencywide Documents Access and Management System", 
"ADF":"Application Development Framework", 
"ADI":"Accurate Dispersions Inc.", 
"ADO":"Area Director of Operations", 
"ADP":"Automatic Data Processing", 
"AE":"Application Enabler (11.0)", 
"AEC":"Alkyd Emulsion Chemical", 
"AED":"Automated External Defibrillator", 
"AES":"Automated Export System", 
"AF":"Approve to Fill", 
"AF":"Automotive Finishes", 
"AFD":"Automotive Finishes Division", 
"AFSO":"Assistant Facility Site Organizer", 
"AFWC":"Away From Work Case", 
"AGD":"American Gage Design Standards", 
"AGP":"Accelerated Graphics Port", 
"AGV":"Automated Guided Vehicle", 
"AHT":"Average Handle Time", 
"AIA":"Application Integration Architecture", 
"AIAG":"Automotive Industry Action Group", 
"Ajax":"Asynchronous JavaScript and XML", 
"AJAX":"Asynchronous JavaScript and XML", 
"ALM":"Automation system", 
"AM":"Audit Management", 
"AMS":"Audit Management System", 
"AMS":"After Market Services", 
"ANI":"Automated Numbering Identification", 
"ANOM":"Analysis of Means", 
"ANOVA":"Analysis of Variation", 
"ANOVA":"Analysis of Variance", 
"ANSI":"American National Standards Institute", 
"AOM":"Advanced Order Management", 
"AOQ":"Average Outgoing Quality", 
"AOQL":"Average Outgoing Quality Limit (Level)", 
"AP":"Oracle's acronym for Accounts Payable", 
"AP":"(Oracle) Advanced Pricing ", 
"AP":"Associated Products", 
"AP":"Asia Pacific", 
"APC":"Air Pollution Control", 
"APDC":"Associated Product Distribution Center", 
"API":"Application Programming Interface", 
"APICS":"American Production and Inventory Control Society", 
"APL":"Acceptable Process Level", 
"Application Enabler":"Application Enabler", 
"APQP":"Advanced Product Quality Planning ", 
"APS":"Arizona Public Service", 
"AQCR":"Air Quality Control Region", 
"AQIP":"Academic Quality Improvement Project", 
"AQL":"Acceptable Quality Level/Limit", 
"AQM":"Aspect Quality Management", 
"AQP":"Association for Quality and Participation", 
"AR":"Accounts Receivable", 
"ARB":"Avoid Reset Broadcast", 
"ARC":"Accelerated Root Cause", 
"ARC":"Analytical Resource Center", 
"Architectural":"Architectural", 
"ARJV":"Account Receivable Journal Voucher ", 
"ARL":"Average Run Lengths", 
"ARS":"Authorized Return Service", 
"ART":"Automated Reconcile Tracking", 
"AS":"Applicability Statements", 
"AS1":"Applicability Statements 1", 
"AS2":"Applicability Statements 2", 
"AS3":"Applicability Statements 3", 
"ASCII":"American standard code for information interchange", 
"ASCP":"Advanced Supply Chain Planning", 
"ASME":"American Society for Mechanical Engineers", 
"ASN":"Advanced Shipping Notice (EDI 856)", 
"ASN":"Average Sample Number", 
"ASNT":"American Society for Nondestructive Testing", 
"ASO":"Aggregate Storage Option", 
"ASQ":"American Society for Quality", 
"ASQC":"American Society for Quality Control", 
"ASQE":"Advanced Supplier Quality Engineering", 
"ASTD":"American Society for Training and Development", 
"ASTM":"American Society for Testing and Materials", 
"ATARG":"Authorisation to Action Return of Goods", 
"ATI":"Average Total Inspection", 
"ATL":"Audit Team Leader", 
"ATP":"Acceptance Test Plan", 
"AU":"Asset Utilization", 
"AUTOCASH":"Automated Cash", 
"AV":"Appraiser Variation", 
"AVRT":"Averitt", 
"AWCS":"Automated Warehouse Control System / GSC's Order Shipping System", 
"AWMA":"Air and Waste Management Association", 
"AWQC":"Ambient Water Quality Criteria", 
"AWSTC":"Arthur W. Steudel Technical Center", 
"AWX":"Waterborne System", 
"B&H":"Brigde and Highway", 
"B2B":"Business to Business", 
"B2B":"Box to Box", 
"B2C":"Business to Customer", 
"B2E":"Business to Employee", 
"BA":"Business Analyst", 
"BACM":"Best available control measures", 
"BACT":"Best Available Control Technology", 
"BAI2":"Bank Administration Institute", 
"BAM":"Business Activity Monitoring (11.0)", 
"BAMS":"Bank of America Marketing System", 
"BASB":"Billed AS / Should Be", 
"BAT":"Best Available Technology", 
"Batch Date":"Batch Date", 
"Batch Fill Lot":"Batch Date", 
"Batch Lot":"Batch Lot", 
"BC":"Brand Code", 
"BCS":"Bar Code Shipping", 
"BE":"Brand Excellence", 
"Beyond Oracle Functionality":"Beyond Oracle Functionality", 
"BFL":"Batch Fill Lot", 
"BI":"Business Intelligence", 
"BIF":"Boilers and Industrial Furnaces", 
"BIF":"Business Improvement Forum", 
"BIFMA":"Business & Institutional Furniture Manufacturer's Assoc.", 
"Blanket Return":"Blanket Return", 
"Blending":"Blending", 
"BMA":"Brokers Marking Analysis", 
"BMP":"Best Management Practices", 
"BMS":"Brand Management System", 
"BMS":"Business Management System", 
"BO":"Business Objects ", 
"BOB":"Best of Breed", 
"BOC":"Batch-Out-of-Control", 
"BOD":"Budget o d", 
"BOF":"Beyond Oracle Functionality", 
"BOHV":"Balance On Hand Value", 
"BOK":"Body of Knowledge", 
"BOL":"Bill of Lading", 
"BOM":"Bill of Material", 
"BP":"Best Practice", 
"BPEL":"Business Process Execution Language", 
"BPI":"Business Process Improvement", 
"BPM":"Business Process Modeling (11.0)", 
"BPM":"Business Process Management", 
"BPM":"Business Process Management", 
"BPMN":"Business Process Model and Notation", 
"BPO":"Business Process Owner", 
"BPR":"Biocidal Products Regulation", 
"BPS":"Business Process Structure", 
"BR":"Basic Requirement", 
"BR":"Blanket Return", 
"BR100":"BR100", 
"Brand Code":"Brand Code", 
"Brand Excellence":"Brand Excellence", 
"BRC":"Business Resource Centre", 
"BRE":"The OnBase Business Rules Engine ", 
"Break-through Time":"Break-through Time", 
"BRS":"Biennial Reporting System", 
"BRXS":"Braun's Express", 
"BSI":"British Standards Institute", 
"BSO":"Block Storage Option", 
"BSR":"Board of Standards Review", 
"BTC":"Breen Technology Center", 
"BTP ":"Book to Perpetual inventory reconciliation", 
"BTU":"British Thermal Units", 
"Building Materials":"Building Materials", 
"Business Objects ":" A Querying / Reporting tool that allows a user to create customized reports using data from multiple databases such as EBR and Product Vision.", 
"Business Rules Engine ":"The OnBase Business Rules Engine (11.0)", 
"BUSOBJ":"Business Object schema for reporting", 
"Buyout":"Buyout", 
"BVO":"Buyer Value Option", 
"C&E":"Cause and Effect Diagram", 
"C2C":"Customer-to-Customer", 
"CA":"Corrective Action ", 
"CAA":"Clean Air Act", 
"CAAA":"Clean Air Act Amendments", 
"CAD":"Canadian Dollars", 
"CAD/CAM":"Computer-Aided Design/Computer-Aided Mfg", 
"CAE":"Computer-Aided Engineering", 
"CAL":"Client Access License ", 
"Calc Manager":"Business rules manager", 
"CAM":"Computer-Aided Mfg", 
"CAN/MEX":"Canada/Mexico", 
"CANICO":"CANICO", 
"CAPA":"Corrective Action, Preventive Action", 
"CAQ":"Condition Adverse to Quality", 
"CAQ or (S)CAQ":"Significant Condition Adverse to Quality", 
"CAR ":"Corrective Action Request/report", 
"CARC":"Chemical Agent Resistant Coating", 
"CARMS":"Credit and Accounts Receivable Management System", 
"CAS":"Chemical Abstract Service", 
"CASE":"Computer-aided Software Engineering", 
"CAT":"Corrective Action Team", 
"CBG":"Consumer Brands Group", 
"CBT":"Computer-based Training", 
"CBV":"Carton Barcode Verifier", 
"CC":"Chemical Coatings", 
"CC":"Critical Characteristic", 
"CCA":"Contact Center Anywhere", 
"CCD":"Coil Coatings Division", 
"CCM":"Collaborative Content Management", 
"CCM":"Collaborative Content Management", 
"CCN":"Cost Center Nucleus", 
"CCT":"Certified Calibration Technician", 
"CDAT":"Code Description Amount Tank", 
"CDATS":"Code, Description, Amount Tank, Sequence", 
"CDI":"Customer Data Interchange", 
"CDI":"Customer Data", 
"CDM":"Centralized Delivery Management", 
"CE":"Oracle's acronym for Cash Management", 
"CE":"Concurrent engineering", 
"CEM":"Continuous Emission Monitors", 
"CEP":"Chicago Emulsion Plant", 
"CERCLA":"Comprehensive ENV Response, Compensation & Liability Act", 
"CERCLIS":"CERCLA Information Service", 
"Certified RM":"OnBase Certified Records Management (11.0) ", 
"CESQG":"Conditionally Exempt Small Quantity Generator", 
"CFATS":"Chemical Facility Anti-Terrorism Standards", 
"CFL":"Colony Forming Units", 
"CFM":"Cubic Feet per minute", 
"CFR":"Code of Federal Regulations", 
"CFS":"Customer Financial Services", 
"CFS Credit":"Customer Financial Services Credit", 
"CFS Proof":"Customer Financial Services Proof", 
"CFSC":"Customer Financial Services Credit", 
"CFSP":"Customer Financial Services Proof", 
"CG":"Consumer Group", 
"CGI":"Commercial Grade Item", 
"CGMP":"Current Good Manufacturing Practices", 
"Changeover":"Changeover", 
"Check 21":"Check 21", 
"ChemSec":"Chemical Security (System)", 
"CHEMSEC":"Chemical Security (System)", 
"CHEP":"Commonwealth Handling Equipment Pooling", 
"CHESAR":"Chemical Safety Assessment and Reporting tool", 
"CHIPS":"Compliant Handling and Investigative Procedures System", 
"CHIPs":"Complaint Handling Investigation Procedures Tech Service", 
"Chrome":"Chrome", 
"CHUB":"Commerce Hub", 
"CHWK":"Check Weigher Kick-off", 
"CI":"Continuous Improvement", 
"CI":"Consignment Inventory ", 
"CI Lean":"Continuous Improvement Lean", 
"CIFS":"Common Internet File System", 
"CILean":"Continual Improvement Lean", 
"CILean":"Continuous Improvement Project", 
"CIP":"Construction in Progress", 
"CIP":"Consolidated Incentive Plan", 
"CIP":"Company Information Sheet", 
"CIS":"Centerline", 
"CL":"Closed-loop corrective action", 
"CLCA":"Command Line Interface", 
"CLI":"Command Line Interface", 
"CLP":"Classification, Labeling, and Packaging", 
"CLS ":"Confirm Label Scanner", 
"CLSW":"Corrective Maintenance", 
"CM":"Content Management", 
"CMM ":"Computerized Maintenance Management System", 
"CMMS":"Complex Maintenance Repair Operations", 
"CMRP":"Certified Material Test Report", 
"CMS":"Central Management Server", 
"CMTR":"Cost Center Nucleus", 
"CNP":"Chart Of Accounts", 
"COA":"Certificates of Analysis", 
"COA":"Certificate Of Compliance", 
"COC":"Certificate of Compliance", 
"COD":"Cash on Delivery", 
"COD":"Chemical Oxygen Demand", 
"COD":"Color On Demand", 
"COD":"COLD/Enterprise Requirement Management", 
"CODND":"Cost of Doing Nothing Differently", 
"COI":"Chemical of Interest", 
"COLD/ERM":"COLD/Enterprise Requirement Management", 
"Collaboration":"OnBase Collaboration (11.0)", 
"Color Lab":"Color Lab", 
"Color on Demand":"Color on Demand", 
"COM":"Continuous Mill", 
"COMAH":"Control Major Accident Hazard", 
"Comex":"Comex", 
"ComPFP":"Oracle Project Financial Planning", 
"ComWFP":"Oracle Workforce Planning", 
"Concur ":"Online tool used to report company expenses that have been charged to your American Express Card.", 
"Consigned":"Consigned", 
"Consumer Group":"Consumer Group", 
"Continue Sale":"Continue Sale", 
"Continuous Improvement":"Continuous Improvement", 
"Controlled Distribution":"Controlled Distribution", 
"Conventional Loan":"Conventional Loan", 
"COO":"Communities of Practice", 
"CoP ":" Communities of Practice: A group of individuals with the same interest or knowledge in a subject matter that meet to discuss issues or develop new ideas and concepts in that area in order to utilize their collective knowledge and experiences. There are 1", 
"COP ":"Cost Of Poor Quality", 
"COPQ":"Cost of Poor Quality", 
"COQ":"Critical Operating Tasks", 
"CoRAP":"Community Rolling Action Plan", 
"Corporate Division":"Corporate Division", 
"Cost Center":"Cost Center", 
"Cost per gallon":"Cost per gallon", 
"Cost per hundred weight":"Cost per hundred weight", 
"Cost per mile":"Cost per mile", 
"Cost Pricelist":"Cost Pricelist", 
"COT":"Collection Plan", 
"COTS":"C Off The Shelf", 
"CP":"Capability ratio (statistical formulas)", 
"CP":"Control Plan", 
"CP":"Cycles Per Batch", 
"CPB":"Continuing Professional Development", 
"CPD":"Cost Per Gallon", 
"CPG":"Customer Product Group", 
"CPG":"Cost Per Hundred Weight", 
"CPHW":"Continuous Process Improvement", 
"CPI":"Competitive Product Information Utilization", 
"CPIU":"Competitive Product Information Utilization", 
"CpK":"Cost Per Mile", 
"CPM":"Customer Product Manager", 
"CPR":"Customer Processing and Repository", 
"CPR":"Complaint Process Resolution ", 
"CPR":"Capital Project Update Report", 
"CPUR ":" Capital Project Update Report", 
"CQA":"Certified Quality Manager", 
"CQT":"Certified Quality Technician", 
"CRADLE":" Creative Research And Development Laboratory Environment – An offsite location in Valley View Ohio which provides additional laboratory space for entrepreneurs who test and develop potential products of interest to SW.", 
"CRL":"Central Receiving Location", 
"CRM":"1. Certified Records Management 2. Customer relationship management",
"CRM":"Certified Records Management - OnBase", 
"CRM":"Customer Relationship Management", 
"CROA":"Critical Order of Addition", 
"Cross Fills":"Cross Fills", 
"CRP":"Conference Room Pilot", 
"CRS":"Cold Rolled Steel", 
"CS":"Customer Service", 
"CS":"Customer Satisfaction", 
"CSA":"Chemical Safety Assessment", 
"CSC":"Customer Service Center", 
"CSFIs":"Counterfeit, Substandard, and Fraudulent Items", 
"CSR":"Chemical Safety Report", 
"CSS":"Customer Service Systems", 
"CSSBB":"Certified Six Sigma Black Belt", 
"CSSTARS":"CSSTARS", 
"CTA":"Call-To-Action", 
"CTI":"Computer Telephony Integration", 
"CTM ":"Cleveland Technical Memorandum", 
"CTMG":"Central Truckload Management Group", 
"C-TPAT":"Customs-Trade Partnership Against Terrorism", 
"CTQ":"Critical To Quality", 
"CTR":"Click-Thru Rate", 
"CTS":"Contract Transportation Systems ", 
"CTSN":"Contract Transportation Systems National", 
"CTU":"Cargo Transport Unit", 
"CU":"Comprehensive Update", 
"Custom Phrases":"Custom Phrases", 
"Customer Data":"Customer Data", 
"CV":"CalendarView (12.0)", 
"CVD":"Chemical Vapor Deposition", 
"CVI":"Chemical Vulnerability Infiltration", 
"CVS":"Concurrent Version System", 
"CWA":"Clean Water Act", 
"CWQC":"Company Wide Quality Control", 
"CWT":"Centum WeighT", 
"Cycles per batch":"Cycles per batch", 
"CYGWIN":"CYGWIN", 
"DAD":"Division Area District", 
"DAM":"DAM Maintenance", 
"DART":"Days Away & Restricted Time ", 
"Dashboard ":"Dashboard ", 
"DB":"Diversified Brands", 
"DB":"Distressed Batch", 
"DBA":"Database Administrator", 
"DBA":"Design Basis Accident", 
"DBD":"Diversified Brands Division", 
"DBI":"Daily Business Intelligence", 
"DC":"Distribution Center", 
"DCI":"Data Center Inventory", 
"DCO":"District Credit Office", 
"DCS":"Division Customer Service", 
"DCS":"Division Customer Service", 
"DDI":"Distribution Data Inc", 
"DDI":"Dynamic Document Information", 
"DDJS":"Distributors/Dealers/Jobbers/Shops", 
"DDO":"Days Deduction Outstanding", 
"DDS":"Distributed Disk Services (11.0) ", 
"DE":"Delta E", 
"DE":"Destruction Efficiency", 
"Debit Types":"Debit Types", 
"DEC":"Department of Environmental Conservation", 
"DELFOR":"Delivery Schedule", 
"DELJIT":"Delivery Just In Time", 
"DEP":"Department of Environmental Protection", 
"DEQ":"Department of Environmental Quality", 
"DESADV":"Dispatch Advice", 
"Descartes":"Descartes Route Planner ", 
"Desktop Document Imaging":"OnBase Desktop Document Imaging (11.0)", 
"Desktop Intelligence":"Business Objects Desktop Intelligence", 
"DEV":"Development", 
"DFA":"Design For Assembly", 
"DFM ":"Design For Manufacturability", 
"DFMEA":"Design Failure Mode & Effect Analysis", 
"DFSS":"Design for Six Sigma", 
"DHCP":"Dynamic Host Configuration Protocol", 
"Digital Signatures":"OnBase Digital Signatures (11.0)", 
"DIO":"Data Integrity Organization", 
"DIP":"Document Import Processor (11.0)", 
"DISCOVERY":"Discovery", 
"Discovery/NNCDB":"Discovery/NNCDB", 
"Distressed Batch":"Distressed Batch", 
"Diversified Brands Division":"Diversified Brands Division", 
"Division":"Division", 
"DIY":"Do-It-Yourselfer or Homeowner", 
"DKT":"Document Knowledge Transfer (11.0) ", 
"DL":"Delta Lightness", 
"DM":"Demand Management", 
"DMADV":"Define, Measure, Analyze, Design, and Verify", 
"DMAIC":"Define, Measure, Analyze, Improve, and Verify", 
"DMI":"Data Mart", 
"DMI":"Daily Maintenance Intelligence Reports", 
"DMO":"Data Maintenance Organization", 
"DMZ":"De-Militarized Zone", 
"DNEL":"Derived No-Effect Level", 
"DNR":"Department of Natural Resources", 
"DNRC":"Department of Natural Resources and Conservation", 
"DNS":"Domain Name System", 
"DocComp":"Document Composition (11.0) ", 
"DocImport":"Document Importer", 
"DocPOP":"Document POP", 
"DocType":"Document Type", 
"DocTypeGroup":"Document Type Group", 
"DocTypeGrp":"Document Type Group", 
"Document Composition":"OnBase Document Composition (11.0) ", 
"DOE":"Design of Experiments", 
"DOE":"Direct Order Entry", 
"DOT":"Department of Transportation", 
"DP":"Development Process", 
"DPE":"Dopeler Effect", 
"DPMO":"Defects Per Million Opportunities", 
"DPTO":"Defects Per Thousand Orders", 
"DR":"Disaster Recovery", 
"DRA":"Directory Resource Administrator", 
"DRE":"Destruction and Removal Efficiency", 
"DRG":"Oracle Data Relationship Governance", 
"DRM":"Oracle Data Relation Management", 
"DRP":"Disaster Recovery Plan", 
"DRP":"Distribution Requirements Planning Purchasing", 
"DSC":"Distribution Service Centers", 
"DSO":"Daily Sales Outstanding", 
"DT ":"Destructive Testing", 
"DTO":"Do The Obvious", 
"DV":"Design Verification", 
"DVCS":"Distributed Version Control Software", 
"DVW":"Design Validation Workshop", 
"DYB":"Delta Yellow Blue", 
"EA":"Eastern", 
"EAD":"Eastern Division", 
"eAM":"Enterprise Asset Management", 
"EARA":"Environmental Auditors Registration Association (now IMEA)", 
"EAS Console":"Essbase Administration Service Console", 
"East Region":"East Region", 
"EBOL":"Electronic Bill of Lading", 
"EBR":"Electronic Bench Record", 
"EBS":"eBusiness Suite", 
"eBS":"e Business Suite", 
"EC":"EC Numbers", 
"ECAO":"Environmental Criteria and Assessment Office", 
"ECCS":"Emergency Core Cooling System", 
"ECHA":"European Chemicals Agency", 
"ECM":"Enterprise Content Management", 
"ECN":"Engineering Change Notice", 
"ECO":"Engineering Change Order", 
"EcoMet":"EcoMet", 
"eCOMMIT":"eCOMMIT", 
"eCommit ":" Lotus Notes-based", 
"eCopy Trace Log":"eCopy Trace Log", 
"EcoVision":"EcoVision", 
"ECR":"Engineering Change Request/Release", 
"EDA":"Employee Direct Access", 
"EDI":"Electronic Data Interchange", 
"EDIFACT":"Electronic Data Interchange For Administration, Commerce, and Transport", 
"EDIFECT INVRPT":"EDI FECT Inventory Report", 
"EDIINT":"EDI over the INTernet", 
"EDMS":"Electronic Data Management System", 
"EDS":"Electronic Data Sheet", 
"EE":"Eligible Employee", 
"EEX":"Environmental Excellence", 
"eFCA":"Electronic Fixed Capital Appropriation ", 
"eForm":"eForms (11.0)", 
"eFORM":"eFORM", 
"EGWP":"Employee Group Waiver Plan", 
"EH & RS":"Environmental Health & Regulatory Services", 
"EHRS":"Environmental Health Regulatory Services Regulatory", 
"EHS":"Environmental Health Services", 
"EHS&S":"Environmental Health Safety & Sustainability", 
"EHSMS":"Environmental Health & Safety Management System", 
"EI":"Employee Insurance", 
"EI":"External Innovation", 
"EID":"Employee Identification Number in LDAP", 
"EIID":"Element Identifier", 
"EIS":"Executive Information System", 
"EISL":"Expansion Inter Site Link", 
"ELID":"Element Identifier", 
"ELMS":"Electronic Legal Management System", 
"EM":"Enterprise Management", 
"EM":"Emerging Markets", 
"EMEA":"Europe, Middle East, & Africa", 
"EMEA":"Europe, Middle East, & Africa", 
"Emerging Markets":"Emerging Markets", 
"EMMA":"Expired Materials Management", 
"EMP":"Environmental Management Plan", 
"EMS":"Environmental Management System", 
"Eng Project Summary":"Eng Project Summary", 
"EOCA":"European Organization for Conformity Assessment", 
"EOM":"End Of Month", 
"EOY":"End Of Year", 
"EPA":"Environment Protection Agency", 
"EPCRA":"Emergency Planning and Community Right-to-know Act", 
"ePIC":"electronic Prior Informed Consent", 
"EPM":"Enterprise Performance Management", 
"EPM SCM":"Supply Chain Management application in EPM Cloud", 
"EPRI":"Electric Power Research Institute", 
"EPS":"Engineered Polymer Solutions", 
"EPS":"Engineered Polymer Science", 
"EPS":"Engineering Project Summary", 
"EPSP":"Employee Purchase Savings Plan", 
"ERC":"Emergency Response Coordinator", 
"ERG":"Emergency Response Guidebook", 
"ERIS":"Employee Relations Issue System", 
"ERP":"Enterprise Resource Planning", 
"ES":"Exposure Scenario", 
"ESD":"Electrostatic Discharge", 
"ESL":"End Service Layer", 
"Essbase":"Extended Spread Sheet Database", 
"E-Stop":"Emergency Stop", 
"ETA":"Estimated Time Arrival", 
"ETL":"Extract Transformation Load", 
"ETRAC":"Electronic Tracking of Returns And Credits", 
"EU":"European Union", 
"EVDO":"EVDO", 
"EVOP":"Evolutionary Operations", 
"EWMA":"Exponentially Weighted Moving Averages", 
"Excellence Initiatives":"Excellence Initiatives", 
"Exceptions to Policy":"Exceptions to Policy", 
"EXIS":"Expert Information Systems", 
"Exis ":"Exis ", 
"EXLA":"Estes Express", 
"Expedite Request":"Expedite Request", 
"Export":"Export (11.0) ", 
"F/T":"Freeze Thaw", 
"FA ":"Fixed Assets", 
"FACTS":"Financial Analysis Control & Tracking System", 
"FAS":"Field Audit Supervisor", 
"FAST":"Fully Automated Storage Tiering", 
"FCA":"Fixed Capital Authorization", 
"FCCS":"Financial Consolidation and Close Cloud Service", 
"FCN":"Food Contact Notification", 
"FCS":"Facility Control Systems", 
"FD":"Field Destroy", 
"FDMEE":"Oracle Hyperion Financial Data Quality Management, Enterprise Edition", 
"FDO":"Ft Dearborn Orders", 
"FE":"Financial Excellence", 
"FEA":"Finite Element Analysis", 
"FEITH":"FEITH", 
"FES":"Federal Engineering Systems", 
"FF":"Freight Forwarders", 
"FGOB":"Finished Good Outside Buy", 
"FHA Loan":"Federal Housing Authority Loan", 
"FIFO":"First In, First Out", 
"FIFRA":"Federal Insecticide Fungicide and Rodenticide Act", 
"File Format":"File Format", 
"Fill":"Fill", 
"Fill line efficiency":"Fill line efficiency", 
"Fill Lot":"Fill Lot", 
"Fill Rex":"Fill Rex", 
"FIM":"Forecast Index Model", 
"Financial Adjustments":"Financial Adjustments", 
"Financial Creation":"Financial Creation", 
"Financial Creation Delays":"Financial Creation Delays", 
"Financial Excellence":"Financial Excellence", 
"Financial Mapping Delays":"Financial Mapping Delays", 
"Financial Transactions":"Financial Transactions", 
"FIPS":"Federal Information Processing Standards codes", 
"Firefox":"Firefox", 
"FL":"Fill Lot", 
"Flash":"Flash", 
"FLASH":"FLASH  ", 
"FLE":"Fill Line Efficiency", 
"FLM":"Fill Line Manager", 
"FLP":"Fill Line Putaway", 
"FLPT":"Flash Point", 
"FM":"Field Monitors ", 
"FM":"Functional Manager", 
"FMAP":"Formula Manufacturing Assurance Program", 
"FMEA":"Failure Mode & Effect Analysis", 
"FMLA":"FMLA", 
"FN":"Foreign National", 
"FOC":"Ford of Canada", 
"Focus Areas":"Focus Areas", 
"FOLDER POP":"FOLDER POP", 
"FolderPOP":"FolderPOP", 
"FOS":"FOS", 
"FP":"Flash Point ", 
"FPC":"Factory Package Color", 
"FR":"Federal Register", 
"FR":"Fill Rex", 
"FRA":"Federal Insecticide, Fungicide, Rodenticide Act ", 
"FRS":"Financial Reporting Studio", 
"FS":"Forecasted Stock", 
"FSAH":"Financial Services Accounting Hub", 
"FSG":"Financial Statement Generator", 
"FSO":"Facility Site Organizer", 
"FSS":"Financial Shared Services", 
"FTA":"Fault Tree Analysis", 
"FTE":"Full Time Employee", 
"FTP":"File Transfer Protocol", 
"FTS":"Field Technical Sales", 
"FTT":"First Time Through", 
"FTY":"First Time Yield", 
"FVO":"Full Buyout Value", 
"FWT":"FWT", 
"GB":"Green Belt", 
"GBMS":"Global Business Management System Quality", 
"GBS":"Global Business Service", 
"GCOC":"General Certification of Conformity", 
"GD&T":"Geometric Dimensioning and Tolerancing", 
"GDB":"GDB", 
"GEC":"Global Electronic Commerce", 
"GEMS":"Global Employee Management System", 
"General Polymers":"General Polymers", 
"Geocel":"Geocel", 
"GERP":"Global Enterprise Resource Planning", 
"GERT":"Graphical Evaluation and Review Technique", 
"GFG":"Global Finishes Group", 
"GFP":"Global Footprint", 
"GHD":"Global Help Desk", 
"GHS":"Globally Harmonized System", 
"GI":"General Industrial Division", 
"GID":"Gems Employee ID", 
"GIMP":"GIMP", 
"GIS":"Gentran Information Suite", 
"GL":" General Ledger", 
"GLM":"General Linear Modeling", 
"GLP":"Good Laboratory Practices ", 
"GMP":"Good Manufacturing Practice", 
"GMSPO":"General Motors Special Purchase Order", 
"GOM":"Goods of Manufacture", 
"Good Faith Estimate":"Good Faith Estimate", 
"GP":"Generic Paint", 
"GPA":"Group Policy Admin", 
"GPL":"General Public License", 
"GPM":"Graphic Process Modeler", 
"GPO":"Group Policy Objects", 
"GPS":"Global Planning System", 
"GR&R":"Gage repeatability and reproducibility", 
"GRC":"Governance, Risk, Compliance", 
"GRE":"Governance Report Entity", 
"Green":"Green", 
"GREEN":"GREEN  ", 
"Gross":"Gross", 
"GRPC":"Global Regulatory Product Compliance", 
"GSA":"General Services Administration", 
"GSC":"Global Supply Chain Division", 
"GSC Regions":"GSC Regions", 
"GSC REGIONS":"GSC REGIONS", 
"GSI":"Global Single Instance", 
"GTM":"Global Traffic Manager", 
"GUI":"Graphical User Interface", 
"H-1B":"H-1B", 
"HALS":"H Automated Label System", 
"HAP":"Hazardous Air Pollutant", 
"HAZMAT":"Hazardous Materials", 
"HD":"Help Desk", 
"HEARS":"Health Environmental and Regulatory System", 
"Helper App":"Helper App", 
"HEQ":"Hard Equipment", 
"HFM":"Oracle Hyperion Financial Management", 
"HHG":"House Hold Goods", 
"Hi-Lift":"Hi-Lift", 
"HIS":"HIS", 
"HK ":"House Keeping ", 
"HKE":"HouseKeeping Excellence: Part of the onsite Safety Initiative (see section on Housekeeping Excellence)", 
"HMES":"Holland", 
"HMIS":"Hazardous Materials Identification System", 
"HMR":"Hazardous Materials Regulations", 
"HN":"Help Needed", 
"HOTW":"HEARS On The Web", 
"HOW":"HEARS On Web", 
"HP":"Hewlett-Packard", 
"HQ ":" Headquarters", 
"HR Connect":"HR version of Remedy", 
"HRA":"Human Resource Administration", 
"HRC":"HighRadius Cash Application Cloud", 
"HRMS":"Human Resource Management System", 
"HRPR":"Human Resource Policy Review", 
"HSD":"HSD", 
"HSE":"Health, Safety & Environmental", 
"HSWA":"Hazardous and Solid Waste Amendments of 1984", 
"HTC":"Harmonized Tariff Code", 
"HTML":"Hypertext Markup Language", 
"HTS":"Harmonized Tariff Schedule", 
"HTTP":"Hypertext Transfer Protocol", 
"HUD":"Heads-up Displays", 
"HUD - 1":"Housing Urban Development - 1", 
"Human-Computer Interaction":"Human-Computer Interaction", 
"Hyperion":" Financial reporting tool", 
"HYPERION":"HYPERION", 
"I/W":"Inter Warehouse", 
"I-140":"I-140", 
"i2":"GSC Supply Chain software", 
"i2 AP":"i2 Associated Products", 
"i2 DM":"i2 Demand Manager", 
"i2 SCP":"i2 Supply Chain Planning", 
"IA":"Intelligent Authoring", 
"IAEA":"International Atomic Energy Agency", 
"IAF":"International Accreditaion Forum", 
"IAFRM":"I Accounting Financial R M - Hyland tool", 
"IAM":"Identity Access Management", 
"IAQ":"Indoor Air Quality", 
"IAQG":"International Aerospace Quality Group", 
"IARC":"International Agency for Research on Carcinogens", 
"IAS":"International Accreditation Services", 
"IATA":"IATA", 
"IATF":"International Automotive Task Force", 
"IBAR":"Inventory Billing Adjustment Report", 
"IBAR ":"– Internal Billing Adjustment Report – a paper form taken to a Sherwin-Williams site to purchase paint. All paint purchased from stores must be done using an IBAR. The form can be located on the share drive: S:\Accounting\IBAR process", 
"IBC":"Intermediate Bulk Container", 
"IBM":"International Business Machines", 
"IBR":"Inbound Recovery System", 
"IC":"Individual Contributor", 
"IC":"Information Center", 
"ICM":"Institutional Calibration Methods", 
"ICR":"Inventory Control Report", 
"ICR ":"Inventory Control Record", 
"ICS":"International Classification for Standards ", 
"IDI":"Inter-Division Invoice", 
"IDK":"Invoice Date Key", 
"Idle Assets":"Idle Assets", 
"IDMS":"Integrated Database Management System", 
"IDN":"IdentityNow", 
"Idol":"Full-Text Indexing Server for Autonomy IDOL (11.0)", 
"IE":" Innovation Excellence: One of the Company’s 6 “Culture of Excellence” Initiatives. Innovation Excellence targets and connects the world-wide R&D areas within SW, leveraging best practices across Divisions to enhance communications. The other 5 initiative", 
"IEEE":"Institute of Electrical and Electronic Engineers", 
"IEMA":"Institute of Environmental Management and Assessment", 
"IETF":"Internet Engineering Task force", 
"IFS":"IFS", 
"IFT":"International Fuel Tax", 
"IG":"Initiator Group", 
"IH":"Industrial Hygienist", 
"IHS":"IHS", 
"IIS":"Internet Information Server", 
"ILAC":"International Laboratory Accreditation Cooperation ", 
"IM":"Industrial Maintenance", 
"IM":"Incident Management", 
"IM":"Industrial Mount", 
"IM":"Instant Messenger", 
"Image Files":"Image Files", 
"IMDG":"International Maritime Dangerous Goods", 
"IMDS":"International Material Data System ", 
"IMI":"Industri-Matematik International", 
"IMO":"International Maritime Organization", 
"IMO DGD":"Multimodal Dangerous Goods Declaration", 
"IMT":"Industrial Mounted Terminal", 
"IN":"Information Notice", 
"Incidents":"Incidents", 
"INDICO":"INDICO", 
"InfoBlox":"InfoBlox", 
"INGL/WINGL":"INGL/WINGL ", 
"Intermixes":"Intermixes", 
"Invoice Creation":"Invoice Creation", 
"IOC":"Inorganic Chemical", 
"IP":"Internet Protocol", 
"iP":"iProcurement", 
"IPAM":"Internet Protocol Address Management", 
"IPM":"Image Processing Management", 
"IPPLAN":"IPPLAN", 
"IPUP":"Incremental Parallel Upgrade Process", 
"IQA":"Internal Quality Audit", 
"IQR":"Inventory Quality Ratio", 
"IRC ":"Innovation Resource Center", 
"IRCA":"International Register of Certificated Auditors", 
"IRP":"International Registration Plan", 
"IRR":"Internal Rate of Return", 
"ISA/EISA":"Industry Standard Architecture /Extended Industry Standard Architecture",
"ISIS":"ISIS", 
"ISK":"ISK", 
"ISO":" International Organization for Standardization: BTC is ISO-9001 certified, which requires periodic re-certification by outside auditors. At Sherwin-Williams we use ISO 9001 as a standard for a total Business Management System. It is part of the company’s", 
"ISR":"Inter-Store Receivables", 
"ISR":"Inter Store Request", 
"ISR":"In Store Resolution", 
"IST":"Inter-Store Transfer", 
"IST":"Inoculation Setting pre-Test", 
"IT":"Information Technology", 
"IT":"Information Technology", 
"ITAR":"International Traffic in Arms Regulations", 
"ITM":"International Test Method", 
"ITN":"Internal Transaction Number", 
"IUCLID5":"IUCLID5", 
"IVAN":"Inventory Analysis", 
"IW":"Inter Warehouse", 
"IWA":"International Workshop Agreements", 
"IWD":"Industrial Wood Division", 
"J29":"J29/Special", 
"J-29":"Custom Rush Batch", 
"JAS":"Job Applicant System", 
"JBDS":"JBoss Development Studio", 
"JDA (i2)":"JDA (i2)", 
"JIT":"Just In Time", 
"JRE":"Java Runtime Environment", 
"JSA":"Job Safety Analysis", 
"JTA":"Job Task Analysis", 
"JUSE":"Japanese Union of Scientists & Engineers", 
"JV":"Journal Voucher", 
"K14":"Inter warehouse transfer of finished goods", 
"K17":"Shipment of plant production to warehouse", 
"KAIZEN":"KAIZEN (Translated: GOOD CHANGE)", 
"Kaleidoscope ":" The Sherwin-Williams Company newsletter issued quarterly. Electronic versions can be found on MySherwin, Home tab under employee communications.", 
"Kan Ban":"Kan Ban", 
"KDS":"Key Decision Spreadsheet", 
"Key Decision":"Key Decision", 
"Key User":"Higher level users who will train end users", 
"KL":"Kuala Lumpar, Malaysia", 
"KM":"Knowledge Management", 
"KP":"Kitting Parts", 
"KPI":"Key Performance Indicators", 
"KPIV":"Key Process Input Variables (Project Inputs - Causes)", 
"KPOV":"Key Process Output Variables (Project Outputs - Effect)", 
"KST":"KST", 
"KUT":"Key User Training", 
"KW":"Keywords", 
"L-A-B":"Laboratory Accreditation Bureau", 
"Lab Project / Service Request":"Lab Project / Service Request", 
"LACG":"Latin America Coatings Group", 
"LACG or LAG":"Latin America Coatings Group or Latin America Group.  The latter is more in line with the three letter abbreviations of the other divisions.", 
"LAD":"Latin America Division", 
"LAER":"Lowest Achievable Emission Rate", 
"LAG":"Latin American Group", 
"LAM":"Latin America", 
"LAR":"Large Account Reseller", 
"LASR":"Lab Analytical Service Request", 
"LatAm":"Latin America", 
"Layout/View":"Layout/View", 
"LB":"Load Balancer", 
"LCL":"Lower Control Limit", 
"LDAP":"Lightweight Directory Access Protocol", 
"LDAPSOFT":"Lightweight Directory Access Protocol Software", 
"LDR":"Land Disposal Restrictions", 
"Lean":"Lean", 
"LEE":"Leadership Excellence", 
"LEED":"Leadership in Energy and Environmental Design", 
"LEL":"Lower Explosion Limit", 
"Lifecycle":"Lifecycle", 
"LIFO":"Last in First Out", 
"LIMS":" Laboratory Information Management System: A general term used to describe a suite of in-house applications that consist of the following applications. Note - The LIMS icon can be found in your Application Launcher:", 
"Line Service":"Line Service", 
"Lines":"Lines", 
"LMS":"Learning Management System", 
"LMS":"Learning Management System", 
"LOCA":"Loss of Coolant Accident", 
"LOE":"Lack of Objective Evidence", 
"LOELs":"Lowest Observed Effect Levels", 
"LOI":"Loss Offense Incident", 
"LOLI":"Lists of Lists Inventory", 
"LOS":"Loss of Sale", 
"LOTO":"Lock Out Tag Out", 
"LOV":"List of Values", 
"LPI":"L Printer Interface", 
"LQG":"Large Quantity Generator", 
"LRQ":"Lab Regulatory & Quality", 
"LSL":"Lower Specification Limit", 
"LSMR ":"Loss Spoiled Material Report", 
"LT":"Load Test", 
"LTD QTY":"Limited Quantity", 
"LTL":"Less Than Load", 
"LTL":"Less Than (truck)Load", 
"LTL":"Lower Tolerance Limit", 
"LTM":"Local Traffic Manager", 
"LTPD":"Lot Tolerance Percentage Defective", 
"LUA":"Least User Access support", 
"LUN":"Logical Unit Number", 
"LUNS":"Logical Unit Number Storage", 
"LYR":"Last Year", 
"M&TE":"Measuring and Test Equipment", 
"MACT":"Maximum Achievable Control Technology", 
"MAR":"Meditech Archive Report (file extension)", 
"Margin Credits":"Margin Credits", 
"Marketing":"Marketing", 
"Master Primary Cost":"Master Primary Cost", 
"Master Rex":"Master Rex", 
"MatEval":"Material Evaluation", 
"MAV":"Minimum Acceptable Value", 
"MaxL":"MaxL", 
"MBB":"Master Black Belt", 
"MBM":"Management by Magazine", 
"MBR":"MBR", 
"MCL":"Maximum Contaminant Levels", 
"MCP":"Microbial Control Program", 
"MDI":"Management Dynamic Inc.", 
"MDM":"Mobile Device Management", 
"MDM":"Material Data Management", 
"MDT":"Microsoft Data Translator?", 
"MDX":"MDX", 
"Medina Weathering Station ":"Medina Weathering Station ", 
"MERC":"Manual Entry Reason Code", 
"MES":"Manufacturing Enterprise Systems", 
"Metadata":"Metadata", 
"MFD":"Multi-functional devices", 
"MFG":"Manufacturing", 
"MGLC":"Maximum Ground Level Concentration", 
"MHP":"Manufacturing Hygiene Program", 
"Microsoft Dynamics CRM 2011":"Microsoft Dynamics CRM 2011", 
"MIL-STD":"Military Standard", 
"MIPS":"Matched Invoice Payment System", 
"MIRA":"Management of Change, Incident Management, Risk Analysis, Audit Management", 
"MIS":"Manufacturing Information Systems", 
"MITI":"MITI", 
"ML":"Manufacturing Location", 
"MLPP":"Multi-Language Print Programs", 
"MM ":"Manager of Manager", 
"MMS":"Merchandise Management System", 
"MO":"Manager of Others", 
"MO":"Material Organization", 
"MOB":"Maintenance of Business", 
"Mobius":"Mobius", 
"MOC":"Management of Change", 
"MON":"Miscellaneous Organic NESHAP", 
"Mosaic":"Mosaic", 
"MP&L":"Material Planning & Logistics", 
"MP2":"Maintenance Management 2", 
"MPF":"Master Product File", 
"MPI":"Master Painters Institute", 
"mPOS":"Mobile Point of Sale", 
"MPS":"Master Production Scheduling", 
"MQ":"MQ", 
"MR":"Moving Range", 
"MRA":"Mutual Recognition Arrangement", 
"MRB":"Material Review Board", 
"MRex":"Master Rex", 
"MREX":"Master Rex", 
"MRL":"Manufacturing Readiness Level", 
"MRO":"Maintenance Repair and Overhaul ", 
"MRO":"Maintenance, Repair & Operations/non-Raw Material", 
"MRP":"Material Requirement Planning", 
"MSA":"MSA", 
"MSA":"Management Science of America", 
"MSA":"Measurement Systems Analysis", 
"MSAA":"Microsoft Active Accessibility", 
"MSCA":"Mobile Supply Chain Apps", 
"MSDS":"Material Safety Data Sheet: A form containing data regarding the properties of a particle substance.", 
"MSO":"Multi Shop owner", 
"MSLB":"Main Steam Line Break", 
"MSTSC":"Microsoft Terminal Services Client", 
"MSW":"Municipal Solid Waste", 
"MTD":"Month To Date", 
"MTO":"Make to order", 
"MTS":"Make to stock", 
"MUE Image":"MUE Image", 
"MUG":"Manufacturing User Group", 
"MUI":"Multi User Interface", 
"Multi-Value":"Multi-Value", 
"MV":"Masking View", 
"MW":"MidWest", 
"MW":"Mixed Waste", 
"MWD":"MidWest Division", 
"My Sherwin":"My Sherwin", 
"MySherwin":"MySherwin", 
"NA":"North America", 
"NAAQS":"National Ambient Air Quality Standards", 
"NADCAP":"National Aerospace & Defense Contractors Accreditation Program,", 
"NAFTA":"North American Free Trade Agreement", 
"NAHB":"National Association of Home Builders", 
"NAICS":"North American Industry Classification System", 
"NAL":"Novell Application Launcher", 
"NAPHTHA":"NAPHTHA", 
"NASL":"Nuclear Approved Supplier List", 
"NBS":"National Bureau of Standards", 
"NC":"Non-Conformance", 
"NCCM":"Network Change & Control Management", 
"NCFG":"Non-Conforming Finished Goods", 
"NCP":"National Contingency Plan", 
"NDA":"Non-Disclosure Agreement", 
"NDE":"Nondestructive Examination", 
"NDLV":"Non-Stop Delivery", 
"NDT":"Nondestructive Testing", 
"NEMF":"New England Motor Freight", 
"NESHAP":"National Emission Standard for HAPs", 
"Net":"Net", 
"Netezza":"Netezza", 
"New Products":"New Products", 
"NFA":"No Further Action", 
"NFI":"New Formula Introduction", 
"NFPA":"National Fire Protection Association", 
"NGT":"Nominal Group Technique", 
"NHOT ":" New Hire Orientation Training ", 
"NIAC":"Nuclear Industry Assessment Committee", 
"NIC":"Network Infrastructure Control", 
"NID":"National Identifier Number", 
"NIST":"National Institute of Standards and Technology", 
"NMFA":"National Motor Freight Classification", 
"NMR":"Nuclear Magnetic Resonance", 
"NNCDB":"National Non-Conformance DB", 
"NNSA":"National Nuclear Safety Administration", 
"NOL":"Net Operating Losses", 
"Non Consigned":"Non Consigned", 
"Non-Merch":"Non-Merchandise", 
"Non-preventable accidents":"Non-preventable accidents", 
"NPA":"Non-Preventable Accidents", 
"NPC":"New Product Commercialization", 
"NPD ":"New Product Development", 
"NPDES":"National Pollutant Discharge Elimination System", 
"NPI":"NPI", 
"NPL":"National Priorities List", 
"NQA-1-2008/2009":"Nuclear Quality Assurance-1-2008 ", 
"NRC":"National Response Center", 
"NRC":"Nuclear Regulatory Commission", 
"NSF":"National Sanitary Foundation ", 
"NSI":"NSI", 
"NSPS":"New Source Performance Standards", 
"NSR":"New Source Review", 
"NUPIC":"Nuclear procurement Issues Committee", 
"NVLAP":"National Voluntary laboratory Accreditation Program", 
"NVM":"Non-Volatile Material", 
"O&G":"Oil and Gas", 
"O/O":"Owner/Operators", 
"OAC":"Oracle Analytics Cloud", 
"OAM":"Oracle Access Manager", 
"OAQPS":"Office of Air Quality Planning and Standards", 
"OAS":"Oracle Application Server", 
"OBIEE":"Oracle Business Internal Enterprise Edition", 
"OCI":"Oracle Client Interface", 
"OCR":"Optical Character Recognition", 
"ODBC":"Open Data Base Connection", 
"ODC":"Oracle Document Capture", 
"ODI":"Oracle Data Integrator", 
"OE":"Original Equipment", 
"OEE":"Overall Equipment Effectiveness", 
"OEI":"Original Equipment Interior", 
"OEL":"Occupational Exposure Limits", 
"OEM":"1. Oracle Enterprise Management",
"OEM":"2. Original Equipment Manfacturer",
"OER":"Online Event Registry", 
"OER":"Office of Environmental Restoration", 
"OERR":"Office of Emergency and Remedial Response ", 
"Office Add-In":"Office Add-In", 
"OFI":"Opportunity For Improvement", 
"OFR":"Optical Reader for scanning invoices.", 
"OHS":"Occupational Health System", 
"OIM":"Oracle Identity Management: ", 
"OJT":"On the Job Training", 
"OM":"Oracle's acronym for Order Management", 
"Omni Fill":"Omni Fill", 
"OnBase Document Repository":" A document management system that contains all technical project documents that can be searched across departments and sites.", 
"Onboarding ":" The initial training process for new hires covering the basic functions of starting work at SW.", 
"OO":"Owner/Operator", 
"OP16":"OP16", 
"OP-16":"OP-16", 
"OPEX":"Operational Excellence", 
"OPO":"Oracle Purchase Order", 
"OPP":"Original Purchase Price", 
"OR":"Only Representative", 
"Oracle AP":"Oracle AP", 
"Oracle EAM ":"expense purchasing and preventative maintenance system", 
"Oracle EPBCS":"Oracle Enterprise Planning and Budgeting Cloud Service", 
"Oralce SV":"Oracle SmartView", 
"Order Classes":"Order Classes", 
"Order Completeness":"Order Completeness", 
"Order Creation":"Order Creation", 
"Order Picker":"Order Picker", 
"OSCC":"Open Scape Contact Center", 
"OSHA ":" Occupation Safety & Health Administration", 
"OSND":"Overage Shortage and Damage", 
"OSW":"Office of Solid Waste", 
"OSWER":"Office of Solid Waste and Emergency Response", 
"OTC":"Order to Cash", 
"OTC":"Ozone Transport Commission", 
"OTIF":"On Time In Full", 
"OTMIC":"Off The Mill In-Control", 
"s":"Off The Mill In Spec", 
"OUD":"Oracle Unified Directory", 
"OUST":"Office of Underground Storage Tanks", 
"OW":"Office of Water", 
"P & M":"Protective and Marine Division", 
"P&ID":"Process & Instrument Diagram", 
"P&ID":"Piping & Instrumentation Diagram", 
"P&L":"Profit and Loss statement", 
"P&M":"Protective & Marine Division", 
"P2P":"Point-to-Point", 
"P3":"Paperless Purchasing Process", 
"P3":"P3", 
"PA":"Preventive Action", 
"PA":"Product Availability", 
"Paperless Invoice Workflow ":"Lotus Notes-based application ", 
"PAS":"Promotion and Advertising System", 
"PAS":"Publicly Available Standards", 
"PBT":"Profit Before Tax", 
"PCD":"Packaging Coatings Division", 
"PCG":"Performance Coatings Group", 
"PCI":"Peripheral; Component Interconnect", 
"PCI":"Process Capability Index", 
"PCL":"Printer Control Language", 
"PCR":"Product Cost Request OR Product Change Request", 
"PCR":"Post Consumer Resin", 
"PCS":"Product Certification Sheet", 
"PD":"Oracle's acronym for Product Development", 
"PDCA":"Plan-do-check-act", 
"PDF":"Portable Document Format", 
"PdM":"Predictive Maintenance", 
"PDR":"Project Development Request", 
"PDS":"Product Data Sheet", 
"PDSA":"Plan Do Study Act", 
"PE":"Oracle's acronym for Product Execution", 
"PEL":"Permissible Exposure Limit", 
"PEN test":"Penetration Test", 
"Percy Neyman":"Percy Neyman", 
"Perfect Package Appearance":"Perfect Package Appearance", 
"PET":"Preservative Efficacy Test", 
"PF":"Product Finishes", 
"PFD":"Process Flow Diagram", 
"PFD":"Process Flow Diagram", 
"PFMEA":"Process Failure Mode & Effect Analysis", 
"PFP":"Project Financial Planning", 
"PG":"Port Group", 
"PH":"Physical H…", 
"PHA":"Process Hazard Analysis", 
"PHP":"Hypertext Preprocessor", 
"Phrase":"Phrase", 
"Pi":"Product Introduction", 
"PI1":"PI1", 
"PI2":"PI2", 
"PIC":"Prior Informed Consent", 
"Picking error":"Picking error", 
"PIDS":"Product Information Data Set", 
"PII":"Personally Identifiable Information", 
"PIM":"Product Information Management", 
"PIMD":"Product Initiation, Modification, or Deletion", 
"PIP":"Product Introduction Team", 
"PIT":"Process Improvement Team", 
"PIW":"Paperless Invoice Workflow ", 
"PJLA":"Perry Johnson Laboratory Accreditation", 
"PKS":"Product Kitchen Sink", 
"PLC":"Programmable Logical Controller", 
"PM":"Preventive Maintenance", 
"PMBU":"Pavement Markings b u", 
"PMD":"Protective & Marine Coatings Division", 
"PMD":"Protective & Marine Division", 
"PMIS":"Process Monitoring Information System", 
"PMO":"Project Management Office", 
"PNA":"Program Neighborhood Agent", 
"PNE":"Paint Non-Emulsion", 
"PNEC":"Predicted No-Effect Concentrations", 
"PNL":"Profit and Loss statement", 
"PNO":"Paint Non-Emulsion", 
"PNR":"Problem Notification Report", 
"PO":"Oracle's acronym for Purchase Orders", 
"PO":"Purchase Order", 
"POD":"Professional On Demand", 
"POI":"Perfect Order Index", 
"PONCE":"Price Of Nonconformance", 
"POP":"Points on the Purchase ", 
"Portal":"Portal", 
"Portlets":"Portlets", 
"POS":"Point Of Sale", 
"Post Date":"Post Date", 
"Post-WIMP":"Post-WIMP", 
"Potential Change":"Potential Change", 
"Potential RICE":"Potential RICE", 
"POTW":"Publicly Owned Treatment Works", 
"POV":"Point of View", 
"PP":"Pay Period", 
"PPA":"Perfect Package Appearance", 
"PPA":"Product Planning Analyst", 
"PPAP":"Production Part Approval Process", 
"ppb":"Parts Per Billion", 
"PPE":" Personal Protective Equipment: Safety glasses, shoes, lab coats, respirators, etc.", 
"PPI":"Personally Identifiable Information", 
"PpK":"Preliminary Process Capability Index", 
"PPM":"Product Planning Manager", 
"PPM":"Parts Per Million", 
"PPM":"Project & Portfolio Management", 
"PPMO":"Parts Per Million Opportunities", 
"PPP":"Paid Per Performance", 
"PPPR":"Powdura Powder Project Request", 
"PPS":"Pick, Pack, Ship", 
"PPTO":"Parts Per Thousand Opportunities", 
"PPV":"Purchase Price Variance", 
"PQM":"Plant Quality Manager", 
"PQR":"Product Quality Reporting", 
"PRAT":"Production and Reliability Acceptance Test", 
"PRC":"Price Record Card", 
"Prescient":"Prescient", 
"Privilege Guard":"Privilege Guard", 
"PRM":"Process & Responsibility Matrix", 
"PRN":"Print file (file extension)", 
"PROD":"Production", 
"Product Availability":"Product Availability", 
"Product Data":"Product Data", 
"Product Description":"Product Description", 
"Product Finishes":"Product Finishes", 
"Product recall":"Product recall", 
"Product Types":"Product Types", 
"Professional Conduct":"Professional Conduct", 
"Promotions":"Promotions", 
"Protective Coatings Division":"Protective Coatings Division", 
"PRPs":"Potentially Responsible Parties", 
"PSB":"Paint Sundry Brand", 
"PSD":"PSD", 
"PSG":"Paint Stores Group", 
"PSG transactions not able to post":"PSG transactions not able to post", 
"PSI":"Professional Services Industry", 
"PSIDS":"Payroll Services IDs", 
"PSM":"PSM", 
"PSN":"Proper Shipping Name", 
"PSP":"Paint Service Provider", 
"PSR":"Problem - Solution - Resolution app", 
"PSR":"Product Support Representative", 
"PSSR":"Pre Start-up Safety Review", 
"PSW":"Part Submission Warrant ", 
"PTE":"Potential to Emit", 
"PTP":"Procure to Pay", 
"PTS":"Plant Technical Services", 
"PUD":"Pay on Live Load Pick-Ups and Live Unload Back Haul Deliveries", 
"Purchase Closing Cost":"Purchase Closing Cost", 
"PV":"Product Vision - The global formulation program that contains both production and experimental formulas.", 
"PV":"Production Validation", 
"PV5":"Product Vision v5", 
"PVC":"Pigment Volume Concentration", 
"PVC":"PolyVinyl Chloride", 
"PW":"Prevailing Wage", 
"PWCi":"Proactive Work Capacity Index", 
"PY":"Poka Yoke (Error-Proofing)", 
"QA":"Quality Assurance", 
"QA Hold":"Quality Assurance Hold", 
"QA HOLD":"Quality Assurance HOLD", 
"QAD":"Queen Anne Drive", 
"QAD Order":"QAD Order", 
"QAP":"Quality Assurance Plan", 
"QAR":"Quality Alert Record", 
"QC":"Quality Control (Inspection & Testing)", 
"QE":"Quality Engineer", 
"QEDS":"Quality, Environment, Dependability, Statistics and Social Responsibility", 
"QFD":"Quality Function Deployment", 
"QIA":"Quality Index Audit", 
"QIL":"Quality Investigative Lab", 
"QIL":"Quality Investigation", 
"QIL":"Quality Improvement Laboratories", 
"QLA":"Quality Level Agreement", 
"QM ":"Quality Manual", 
"QMS":"Quality Management System", 
"QN":"Quality Notification", 
"QOS":"Quality Operating System", 
"QP":"Quality Plan", 
"QPP/CPP":"Quabec Pension Plan/Canada Pension Plan", 
"QRP":"Quarterly Reimbursement Process", 
"QS":"Quest Standards", 
"QS":"Quality System", 
"QSAR":"Quantitative Structure-Activity Relationship", 
"QSP":"Quality Standards Program", 
"QTP":"Quick Test Pro", 
"QTS":"Quality Test System", 
"QUEST":"Quality Uniting Excellence, Service & Teamwork", 
"Queue":"Queue", 
"R/T":"Room Temperature", 
"R4BP3":"Register for Biocidal Products", 
"RA":"Return Authorization", 
"RA":"Remedial Action", 
"RA":"Risk Analysis", 
"RAAF":"Read-Across Assessment Framework", 
"RAB":"Registrar Accreditation Board", 
"RAM":"Responsibility & Authority Matrix", 
"RAQ":"Required Air Quantity", 
"RAS":"Reliability/Availability/Maintainability", 
"Raw material usage variance":"Raw material usage variance", 
"RCA":"Roof Condition Assessment", 
"RCA":"Root Cause Analysis", 
"RCFLPT":"Regulatory Certified Flash Point", 
"RCM":"Reliability Centered Maintenance", 
"RCR":"RCR", 
"RCRA":"Resource Conservation and Recovery Act", 
"RDC":"Regional Distribution Center", 
"RDD":"Regional Director of Distribution ", 
"RDI":"Regulatory Data Interface", 
"RDN":"Resource Discovery Network", 
"RDO":"Regional Director of Operations ", 
"RDWY":"Roadway Express", 
"REACH":"Registration Evaluation Age of Chemicals", 
"Readsoft- OCR":"Optical Character Recognition", 
"Recall":"Recall", 
"ReCert":"Recertification", 
"Recordable":"Recordable", 
"ref-cursor":"ref-cursor", 
"Reliability Excellence (Rx)":"A mission of the maintenance organization is to keep assets running in a safe and efficient manner that allows for the production of quality products whenever they are needed.", 
"Reports":"Reports", 
"REST API":"Representational state transfer Application Programming Interface", 
"RET ":"Reverse Engineering Team", 
"RETAD":"Rapid Exchange of Tooling And Dies", 
"Retain Check":"Retain Check", 
"RETL":"Reddaway", 
"Rework":"Rework", 
"RF":"Radio Frequency", 
"RFA":"RCRA Facility Assessment", 
"RFE":"Request for Evidence", 
"RFF":"Reason for Failure", 
"RFI":"RCRA Facility Investigation", 
"RFM":"Regional Facilities Manager", 
"RFO":"Reason for Outage Code", 
"RFP":"Request for Proposal", 
"RFQ":"Request for Quotation", 
"RGA":"Return Goods Authorization ", 
"RI":"Resource Interactive", 
"RICE":"Acronym for Reports, Interfaces, Conversions or Extensions", 
"RICE":"Remedial investigation", 
"RightNow":"RightNow", 
"RIMS":"Returns Information Management System ", 
"RM":"Raw Material", 
"RMA":"Return Merchandise Authorization", 
"RMDM":"Raw Material Data Management", 
"RMIF":"Raw Material Information Form", 
"RMP":"Risk Management Plan", 
"RMS":"Risk Management System", 
"RMV":"Raw Material Variance", 
"ROI":"Return On Investment", 
"RONA":"Return On Net Assets", 
"RO ":"Repair Order", 
"ROS":"Return On Sales", 
"ROW":"Rest of World", 
"RPP":"Registered Pension Plan", 
"RQ":"Reportable Quantity", 
"RQL":"Reject Quality Level", 
"RRC":"Retail Redistribution Center ", 
"RRSP":"Registered Retirement Savings Plan", 
"RSP":"Retirement Savings Plan", 
"RTC":"Reactive Technology Center", 
"RTF":"Rich Text Format (file extension)", 
"RTOS":"Real-Time Operating System", 
"RTS":"Return to Store", 
"RTV":"Return to Supplier", 
"RX":"Reliability Excellence", 
"Rx":"Reliability Excellence", 
"SaaS":"Software as a Service", 
"SAE":"Society of Automotive Engineers", 
"Safari":"Safari", 
"SAGE":"Secrecy Agreement Governance & Evaluation", 
"Sales Excellence":"Sales Excellence", 
"SalesForce.com":"SalesForce.com", 
"SAM":"Sales Analysis Mart", 
"SAN":"Storage Area Network", 
"Sandbox":"Sandbox", 
"SAP CRM":"SAP Customer Relationship Management ", 
"SARA":"Superfund Amendments and Reauthorization Act", 
"SB":"Stock Balance", 
"SBR":"SBR", 
"SC":"Significant Characteristic", 
"SC":"Service Center", 
"SCAC":"Standard Carrier Alpha Code ", 
"SCC":"Serial Container Code ", 
"SCE":"Supply Chain Execution", 
"SCIS":"Supply Chain Information Services ", 
"SCM":"Supply Chain Maintenance", 
"SCOR":"Sales Call Opportunity Reporting", 
"SCP":"Supply Chain Planning", 
"SCRAM":"Safety Control Rod Axe Man", 
"SDC":"Stores Distribution Center ", 
"SDK":"Software Development Kit", 
"SDL":"Specification Design Language", 
"SDM":"Supply Data Management", 
"SDS":"Safty Data Sheet", 
"SDS Pro":"Safety Data Sheet Professional", 
"SDW":"Star Office (file extension)", 
"SDWA":"Safe Drinking Water Act", 
"SDWT":"Self Directed/managed Work Team", 
"SE":"Safety Evaluation", 
"SE":"Southeast ", 
"SED":"Shipper's Export Declaration", 
"SED":"SouthEast Division", 
"SEFL":"Southeastern Freight", 
"SEKO":"Seko Worldwide", 
"SEM":"Strategic Environmental Management", 
"SEO":"Software Engine Optimizer", 
"SER":"Safety Evaluation Report", 
"SFTP":"Secure File Transfer Protocol", 
"SG":"Storage Group", 
"SG&A":"SG&A", 
"SHE":"Safety Health & Environment", 
"SherProcure":"SherProcure", 
"Shipments":"Shipments", 
"Shrink Lines":"Shrink Lines", 
"SHW":"Sherwin-Williams Stock Ticker", 
"SI ":"International System of Units ", 
"SIC":"Standard Industrial Classifications", 
"SIEF":"Substance Information Exchange Forms", 
"SIP":"Session Initiation Potocol", 
"SIPOC":"Supplier Input Process Output Customer", 
"SIT":"Software Integrated Testing", 
"Six Sigma":" A business philosophy that focuses on continuous improvement by understanding customers' needs, analyzing processes, and instituting proper measurement methods. Additionally, it is a methodology that looks to improve key processes by reducing variation. ", 
"Skin":"Skin", 
"SKU":"Stock Keeping Unit ", 
"SLA":"Oracle's acronym for Sub-ledger Accounting", 
"SLA":"Service Level Agreement", 
"SLA":"Sub Ledger Accounting", 
"SLAM":"Strategize, Leverage, Address, Manage", 
"SM":"Sales & Marketing", 
"SMART":"Safety Means Awareness Responsibility Teamwork", 
"SmartCard":"SmartCard", 
"SMB":"Store Merchandise Billing", 
"SME":"Small/Meduim Enterprises", 
"SMED":"Single Minute Exchange Dies ", 
"SMIS":"Stores Management Information System", 
"SMP":"Standard Maintenance Process", 
"SMPO":"SMPO", 
"SMTP":"Simple Mail Transfer Protocol", 
"SNUR":"Significant New Use Rules", 
"SOA":"Service Oriented Architecture", 
"SOAP":"Sale of Old Age Program", 
"SofB":"Set of Books", 
"Software Utilized":"Software Utilized", 
"SOI":"Supplier Owned Inventory", 
"SoIP":"Services over Internet Protocol", 
"SOLAS":"Safety of Life at Sea ", 
"SOMI":"Supplier Owned Maintained Inventory", 
"SOP":"Standard Operating Procedures", 
"SOS":"Special Order SKU", 
"SOSC":"Stores Operation & Supply Chain", 
"SOW":"Statement Of Work", 
"SOX":"Surbanes-Oxley Compliance", 
"Sox Site Checklist":"Sox Site Checklist", 
"SPAM":"Special Products Asset Management", 
"SPC":"Statistical Process Control", 
"SPCC":"Spill Prevention, Control and Countermeasures", 
"Specialty Region":"Specialty Region", 
"SPEX":"Commercial Export Invoice", 
"SPI":"Security Proprietary Information: ", 
"SPOC":"Single Point of Contact", 
"Spoiled Batch":"Spoiled Batch", 
"SQA":"Software Quality Assurance", 
"SQA":"Supplier Quality Assurance", 
"SQC":"Statistical Quality Control", 
"SQG":"Small Quantity Generator", 
"SQI":"Supplier Quality Improvement", 
"SQL":"Structured Query Language", 
"SQR":"Visual SQRibe", 
"SR":"Severity Rating ", 
"SR":"Supplementary Requirement", 
"SRD":"Service Request for Development", 
"SRDF":"System Array Disaster Recovery", 
"SRF":"Service Request Form", 
"SRM":"Service Request for Maintenance", 
"SRM":"Standard Reference Material", 
"SRP":"Sales Rep Portal", 
"SRS":"Software Requirements Specification", 
"SRT":"Service Request Testing", 
"SSHA":"Secure Salted Hashed Algorithm", 
"SSL":"Secure Socket Layer", 
"SSM":"Sales & Service Maintenance", 
"SSO":"Single Sign-On", 
"SSPC":"Society for Protective Coatings", 
"Stage Gate":"Stage Gate", 
"Standard Cost":"Standard Cost", 
"Standard Order":"Standard Order", 
"Standard Store Cost":"Standard Store Cost", 
"STAR":"Stores Transportation And Replenishment ", 
"Status":"Status", 
"STEL":"Short Term Exposure Limit", 
"STEP":"Sales Tax Exemption Processing", 
"STL":"Survey Team Leader", 
"Stop Sale":"Stop Sale", 
"Stores Group":"Stores Group", 
"String Testing":"Beginning to End testing ", 
"STRSASST":"Store's Assistant", 
"STUOM":"Storage Unit of Measure ", 
"StUOM":"Storage Unit of Measure", 
"SU":"Scale Up", 
"SubVar":"Substitution Variables", 
"Success by Design":"Success by Design", 
"Support App":"Support App", 
"Sustainability":"Sustainability", 
"SV":"StatusView", 
"SVG":"Scalable Vector Graphics", 
"SVN":"Subversion", 
"S-W or SW":"Sherwin-Williams", 
"SW TEC":" SW Technical Education Course: ", 
"S-W.com":"The Sherwin-Williams website", 
"SW_HSI":"SW_HSI", 
"SW2000":"SW2000", 
"SWAF":"Sherwin-Williams Automotive Finishes", 
"SWAT":"Sherwin Williams Answer Team", 
"SWD ":"Southwest Division", 
"SWEEP":"Sherwin Williams Enterprise Exchange Process ", 
"SWEEPS":"Sherwin-Williams Enterprise Exchange Process", 
"SWERP":"Sherwin-Williams Enterprise Resource Planning", 
"SWID":"Sherwin-Williams Identity", 
"SWIFT":"Society for Worldwide Interbank Financial Telecommunications", 
"SWIM":"SWIM", 
"SWIS":"Sherwin-Williams Internet Services", 
"SWMU":"Solid Waste Management Unit", 
"SWPPP":"Storm Water Pollution Prevention Plan", 
"SWTEC":"SW Technical Education Course", 
"SWTU":"Sherwin-Williams Training University", 
"SWTU (SWU)":"SWTU (SWU)", 
"SWU":"Sherwin-Williams University", 
"SWU ":"Sherwin-Williams University", 
"SWUK":"Sherwin-Williams United Kingdom", 
"SWUKA":"Sherwin Williams United Kingdom Automotive", 
"SYN":"Syneresis", 
"T&P":"Twist & Pour", 
"TA":"Trade Automation", 
"TAG":"The Americas Group", 
"TAPS":"Transportation Automated Planning System", 
"Tariffs":"Tariffs", 
"TARS":"Technical Assistance Request", 
"TAS":"Thin and Shade", 
"TCLP":"Toxicity Characteristic Leaching Procedure", 
"TCM":"Transactional Content Management", 
"TCO":"Total Cost of Ownership", 
"TCP/IP":"x/Internet Protocol", 
"TD 137":"TD 137", 
"TDG":"Transportation of Dangerous Goods", 
"TDS":"Technical Data Sheet", 
"TDS":"Total Dissolved Solids (mg/L)", 
"Team 150":"Team 150", 
"Terms":"Terms", 
"THC":"Total Hydrocarbons", 
"Tinting":"Tinting", 
"TLM":"Total Lifecycle Management", 
"TLT":"Truck Load Tendering", 
"TLV":"Threshold Limit Value", 
"TMR":"Tri Modular Redundancy", 
"TMW":"Transportation Management W", 
"TOAD":"TOAD", 
"TOC":"Theory Of Constraints", 
"TOC":"Total Organic Carbon", 
"TOD":"Total Oxygen Demand", 
"Toller":"Toller", 
"Total Supply Chain":"Total Supply Chain", 
"TPA":"Trading Partner Agreement", 
"TPM":"Thermoplastic Pavement Marking", 
"TPM":"Total Productive Maintenance", 
"TPS":"Toyota Production System", 
"TQM":"Total Quality Management", 
"TRAC":"TRAC", 
"Trade Name":"Trade Name", 
"Trading Partner":"Trading Partner", 
"Trading Partners":"Trading Partners", 
"Transaction Value Determination":"Transaction Value Determination", 
"Transactional Lean":"Transactional Lean", 
"Transfer Allowance":"Transfer Allowance", 
"Transfer Cost":"Transfer Cost", 
"Transfer Price":"Transfer Price", 
"TRISH":"TRISH", 
"TRIZ":"Theory of Inventive Problem Solving (Translated Russian)", 
"TRV":"Thermal Relief Valve", 
"TS":"Temporarily Stocked ", 
"TS":"Technical Specifications", 
"TSA":"Trypticase Soy Agar", 
"TSD":"TSD", 
"TSDDSS":"TSDDSS", 
"TSDF":"Treatment, Storage and Disposal Facility", 
"TSDR":"Treatment, Storage, Disposal and Recycling", 
"TSO":"Time Sharing Option", 
"TSS":"Total Suspended Solids", 
"Twist and Pour":"Twist and Pour", 
"UAC":"User Access Control", 
"UAS":"Universal Advertising System", 
"UAT":"User Acceptance Testing", 
"UC":"Unified Communications", 
"UCC128":"UCC128", 
"UCL":"Upper Control Limit", 
"UCM":"Universal Content Management", 
"UCVB":"Unknown or Variable composition, Complex reaction products or Biological materials", 
"UDA":"User Defined Attribute", 
"UDF":"User Defined Field", 
"UDPM":"Unstructured Data Policy Management", 
"UEL":"Upper Explosive Limit", 
"UI":"User Interface", 
"UL":"Underwriters Laboratories Inc.", 
"ULT":"Ultimate Source Code at MFG location", 
"Ultimate Source":"Ultimate Source", 
"Uniflex":"Uniflex", 
"Unity":"Unity Client (13.0)", 
"Unity Briefcase":"Unity Briefcase (11.0) ", 
"UNSPSC":"United Nations Standard Product and Services Code", 
"UOM ":" Unit of measure", 
"UPC":"Uniform Product Code ", 
"Updates":"Updates", 
"UPGF":"UPS Freight", 
"UPK":"User Productivity Kit", 
"UPO":"Unidentified Purchase Order", 
"UPSN":"UPS small package", 
"URL":"universal resource locator", 
"US HTS":"United States Harmonized Tariff System", 
"USC":"United States Code", 
"USD":"U.S. Dollars", 
"USL":"Upper Specification Limit", 
"USPS":"United States Postal Service", 
"USR":"Upper Saddle River", 
"UST":"Underground Storage Tank", 
"UTF-16":"16-bit Unicode Transformation Format", 
"UTF-8":"8-bit Unicode Transformation Format", 
"UTL":"Upper Tolerance Limit", 
"UVCB":"Unidentified Variable Component Biological", 
"V&V":"Verification and Validation", 
"VA Loan":"Veterans Administration Loan", 
"VAE":"Value Added Per Employee", 
"VAN":"Value Added Network", 
"Varicent":"Varicent", 
"VAT":"V Acceptance Testing", 
"VB":"Visual Basic", 
"VDA":"Verband der Automobilindustrie", 
"Verity":"Verity", 
"VES":"Vapor Extraction System", 
"Viscosity":"Viscosity", 
"Viscous":"Viscous", 
"Visual Mining":"Visual Mining", 
"VLAN":"Virtual Local Area Network", 
"VM":"Voice Mail", 
"VMI":"Vendor Managed Inventory", 
"VoC":"Voice of the Customer", 
"VOC":"Volatile Organic Compound", 
"VOGUE":"Vertical OnBase Group of User Experts", 
"VoIP":"Voice Over Internet Protocol", 
"VPN":" Virtual Private Network: ", 
"VPP":" Voluntary Protection Program: ", 
"VRF":"Vehicle ReFinish", 
"VRU":"Voice Recognition System", 
"VSA":"Volumn Set Addressing", 
"VSM":"Value Mapping Stream", 
"W1C":"Web #1 Complaint", 
"W2C":"Web #2 Complaint", 
"W3C":"World Wide Web Consortium", 
"WAC":"Weighted Average Cost", 
"WAM":"Web Access Module", 
"Warehouse Cost":"Warehouse Cost", 
"Watson ":"Watson ", 
"WBS":"Work Breakdown Structure", 
"WBT":"Web Based Training", 
"WCM":"Web Content Management", 
"Web Head":"Web Head", 
"WebADI –":" Excel-based spreadsheet ", 
"Web-Util":"Web Utility", 
"Weight":"Weight", 
"West Region":"West Region", 
"WF":"WorkFlow", 
"WF Analytics":"Workforce Analytics", 
"WF Scheduler":"Workforce Scheduler", 
"WHMIS":"Workplace Hazardous Materials Information System", 
"Widget":"Widget", 
"Wiki":"Wiki", 
"WIM":"Workforce Integration Manager", 
"WIMP":"Window, Icon, Menu, Pointing Device", 
"WINS":"Windows Internet Network Service", 
"WIP":"Work In Process", 
"WIT":"Work Improvement Team", 
"WKSH":"Watkins Shepard", 
"WMA":"Waste Management Association", 
"WMS":"Warehouse Management System", 
"WMV":"Windows Media Video (file extension)", 
"WNA":"Windows Native Authentication", 
"WNA":"World Nuclear Association", 
"WO":"Work Order", 
"Wood Care ":"Wood Care ", 
"Woodcare PPP":"Woodcare Pay Per Performance", 
"WPF":"Window Platform Foundation", 
"WPG":"Weight Per Gallon", 
"WSUS":"Windows Server Update Services", 
"WTB":"Where To Buy", 
"WV":"WorkView", 
"WW":"Water and Waste-Water", 
"WWT":"Waste Water Treatment", 
"WYSIWYG":"What you see is what you get", 
"X12":"X12", 
"XF":"Approve to Transfer", 
"XGSI":"Xpress Global Systems", 
"XML":"Extensible Markup Language", 
"XRM":"Extended Relationship Management", 
"ZPA ":"ZScaler Private Access"
}