name: CI/CD Pipeline

on:
  push:
    branches:
      - Kubernetes  # Set this to your default branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: aitranslation.azurecr.io 
        username: AiTranslation 
        password: 5lYJiwLnddzUFrwD9LxNBt/TF4NkVW0pyB74TMXMhe+ACRDCjB8I

    - name: Build and push Docker image
      run: |
        docker build -t aitranslation.azurecr.io/html-translator-service:latest .
        docker push aitranslation.azurecr.io/html-translator-service:latest

    - name: Install Azure CLI
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

    - name: Deploy to Azure Kubernetes Service
      run: |
        az aks get-credentials --resource-group Translator --name AiTranslation
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml