name: Build and deploy Python app to Azure Web App - AI-translations (Excel Features)

on:
  push:
    branches:
      - ExcelFeaturesLauren
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, Linux, X64, sw-ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'

      - name: Check Python installation
        run: |
          echo "Python Executable: $(which python)"
          python --version
          ldd $(which python)

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: [self-hosted, Linux, X64, sw-ubuntu-latest]
    needs: build
    environment:
      name: 'ExcelFeatures'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'AI-translations'
          slot-name: 'ExcelFeatures'
          publish-profile: ${{ secrets.PUBLISHPROFILE_EXCELFEATURESLOT }}
