name: Build and deploy Python app to Azure Web App - AI-translations (Excel Features)

on:
  push:
    branches:
      - ExcelFeaturesLauren
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, macOS, X64]  # Adjust if your runner uses ARM architecture

    steps:
      - uses: actions/checkout@v3

      - name: Install Python
        run: |
          arch -arm64 brew install python@3.8
          echo "export PATH=\"/usr/local/opt/python@3.8/bin:$PATH\"" >> ~/.bash_profile
          source ~/.bash_profile

      - name: Create and start virtual environment
        run: |
          python3.8 -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          python3.8 -m ensurepip
          python3.8 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: [self-hosted, macOS, X64]  # Adjust if your runner uses ARM architecture
    needs: build
    environment:
      name: 'ExcelFeatures'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'AI-translations'
          slot-name: 'ExcelFeatures'
          publish-profile: ${{ secrets.PUBLISHPROFILE_EXCELFEATURESLOT }}
